// Code generated by "stringer -type AccountUniverse -trimprefix Universe"; DO NOT EDIT.

package steamworks

import "strconv"

const _AccountUniverse_name = "InvalidPublicBetaInternalDevuniverseMax"

var _AccountUniverse_index = [...]uint8{0, 7, 13, 17, 25, 28, 39}

func (i AccountUniverse) String() string {
	if i >= AccountUniverse(len(_AccountUniverse_index)-1) {
		return "AccountUniverse(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccountUniverse_name[_AccountUniverse_index[i]:_AccountUniverse_index[i+1]]
}
