// Code generated by "stringer -type AccountInstance -trimprefix Instance"; DO NOT EDIT.

package steamworks

import "strconv"

const (
	_AccountInstance_name_0 = "DesktopConsole"
	_AccountInstance_name_1 = "Web"
	_AccountInstance_name_2 = "FlagMMSLobby"
	_AccountInstance_name_3 = "FlagLobby"
	_AccountInstance_name_4 = "FlagClan"
)

var (
	_AccountInstance_index_0 = [...]uint8{0, 7, 14}
)

func (i AccountInstance) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _AccountInstance_name_0[_AccountInstance_index_0[i]:_AccountInstance_index_0[i+1]]
	case i == 4:
		return _AccountInstance_name_1
	case i == 131072:
		return _AccountInstance_name_2
	case i == 262144:
		return _AccountInstance_name_3
	case i == 524288:
		return _AccountInstance_name_4
	default:
		return "AccountInstance(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
