// Code generated by "stringer -type AccountType -trimprefix AccountType"; DO NOT EDIT.

package steamworks

import "strconv"

const _AccountType_name = "InvalidIndividualMultiseatGameServerAnonGameServerPendingContentServerClanChatP2PSuperSeederAnonUseraccountTypeMax"

var _AccountType_index = [...]uint8{0, 7, 17, 26, 36, 50, 57, 70, 74, 78, 92, 100, 114}

func (i AccountType) String() string {
	if i >= AccountType(len(_AccountType_index)-1) {
		return "AccountType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccountType_name[_AccountType_index[i]:_AccountType_index[i+1]]
}
