// Code generated by "stringer -type Reliability"; DO NOT EDIT.

package steamnet

import "strconv"

const _Reliability_name = "UnreliableUnreliableNoDelayReliableReliableWithBuffering"

var _Reliability_index = [...]uint8{0, 10, 27, 35, 56}

func (i Reliability) String() string {
	if i < 0 || i >= Reliability(len(_Reliability_index)-1) {
		return "Reliability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Reliability_name[_Reliability_index[i]:_Reliability_index[i+1]]
}
