// Code generated by "stringer -type SessionStatus -trimprefix Status"; DO NOT EDIT.

package steamauth

import "strconv"

const _SessionStatus_name = "ClosedUnknownOKUserNotConnectedToSteamNoLicenseOrExpiredVACBannedLoggedInElsewhereVACCheckTimedOutCanceledInvalidAlreadyUsedInvalidPublisherIssuedBan"

var _SessionStatus_index = [...]uint8{0, 6, 13, 15, 38, 56, 65, 82, 98, 106, 124, 131, 149}

func (i SessionStatus) String() string {
	if i < 0 || i >= SessionStatus(len(_SessionStatus_index)-1) {
		return "SessionStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SessionStatus_name[_SessionStatus_index[i]:_SessionStatus_index[i+1]]
}
