// This code is generated by go generate; DO NOT EDIT

#include "shim.h"
#include <steam/steam_api.h>
#include <steam/steam_gameserver.h>

typedef long long intp;

extern "C" bool SteamID_IsValid(uint64 id) { return CSteamID(id).IsValid(); }
extern "C" intp GetSteamClient() { return reinterpret_cast<intp>(SteamClient()); }
extern "C" intp GetSteamUser() { return reinterpret_cast<intp>(SteamUser()); }
extern "C" intp GetSteamGameServer() { return reinterpret_cast<intp>(SteamGameServer()); }
extern "C" intp GetSteamFriends() { return reinterpret_cast<intp>(SteamFriends()); }
extern "C" intp GetSteamUtils() { return reinterpret_cast<intp>(SteamUtils()); }
extern "C" intp GetSteamMatchmaking() { return reinterpret_cast<intp>(SteamMatchmaking()); }
extern "C" intp GetSteamMatchmakingServers() { return reinterpret_cast<intp>(SteamMatchmakingServers()); }
extern "C" intp GetSteamUserStats() { return reinterpret_cast<intp>(SteamUserStats()); }
extern "C" intp GetSteamGameServerStats() { return reinterpret_cast<intp>(SteamGameServerStats()); }
extern "C" intp GetSteamApps() { return reinterpret_cast<intp>(SteamApps()); }
extern "C" intp GetSteamNetworking() { return reinterpret_cast<intp>(SteamNetworking()); }
extern "C" intp GetSteamRemoteStorage() { return reinterpret_cast<intp>(SteamRemoteStorage()); }
extern "C" intp GetSteamScreenshots() { return reinterpret_cast<intp>(SteamScreenshots()); }
extern "C" intp GetSteamHTTP() { return reinterpret_cast<intp>(SteamHTTP()); }
extern "C" intp GetSteamController() { return reinterpret_cast<intp>(SteamController()); }
extern "C" intp GetSteamUGC() { return reinterpret_cast<intp>(SteamUGC()); }
extern "C" intp GetSteamAppList() { return reinterpret_cast<intp>(SteamAppList()); }
extern "C" intp GetSteamMusic() { return reinterpret_cast<intp>(SteamMusic()); }
extern "C" intp GetSteamMusicRemote() { return reinterpret_cast<intp>(SteamMusicRemote()); }
extern "C" intp GetSteamHTMLSurface() { return reinterpret_cast<intp>(SteamHTMLSurface()); }
extern "C" intp GetSteamInventory() { return reinterpret_cast<intp>(SteamInventory()); }
extern "C" intp GetSteamVideo() { return reinterpret_cast<intp>(SteamVideo()); }
extern "C" intp GetSteamParentalSettings() { return reinterpret_cast<intp>(SteamParentalSettings()); }
extern "C" intp GetSteamGameServerClient() { return reinterpret_cast<intp>(SteamGameServerClient()); }
extern "C" intp GetSteamGameServerUtils() { return reinterpret_cast<intp>(SteamGameServerUtils()); }
extern "C" intp GetSteamGameServerNetworking() { return reinterpret_cast<intp>(SteamGameServerNetworking()); }
extern "C" intp GetSteamGameServerHTTP() { return reinterpret_cast<intp>(SteamGameServerHTTP()); }
extern "C" intp GetSteamGameServerInventory() { return reinterpret_cast<intp>(SteamGameServerInventory()); }
extern "C" intp GetSteamGameServerUGC() { return reinterpret_cast<intp>(SteamGameServerUGC()); }
extern "C" intp GetSteamGameServerApps() { return reinterpret_cast<intp>(SteamGameServerApps()); }
