// Code generated by "stringer -type EAccountType -trimprefix EAccountType_"; DO NOT EDIT.

package internal

import "strconv"

const _EAccountType_name = "InvalidIndividualMultiseatGameServerAnonGameServerPendingContentServerClanChatConsoleUserAnonUserMax"

var _EAccountType_index = [...]uint8{0, 7, 17, 26, 36, 50, 57, 70, 74, 78, 89, 97, 100}

func (i EAccountType) String() string {
	if i < 0 || i >= EAccountType(len(_EAccountType_index)-1) {
		return "EAccountType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EAccountType_name[_EAccountType_index[i]:_EAccountType_index[i+1]]
}
