// Code generated by "stringer -type EAppOwnershipFlags -trimprefix EAppOwnershipFlags_"; DO NOT EDIT.

package internal

import "strconv"

const _EAppOwnershipFlags_name = "NoneOwnsLicenseFreeLicenseRegionRestrictedLowViolenceInvalidPlatformSharedLicenseFreeWeekendRetailLicenseLicenseLockedLicensePendingLicenseExpiredLicensePermanentLicenseRecurringLicenseCanceledAutoGrantPendingGiftRentalNotActivatedRentalSiteLicense"

var _EAppOwnershipFlags_map = map[EAppOwnershipFlags]string{
	0:      _EAppOwnershipFlags_name[0:4],
	1:      _EAppOwnershipFlags_name[4:15],
	2:      _EAppOwnershipFlags_name[15:26],
	4:      _EAppOwnershipFlags_name[26:42],
	8:      _EAppOwnershipFlags_name[42:53],
	16:     _EAppOwnershipFlags_name[53:68],
	32:     _EAppOwnershipFlags_name[68:81],
	64:     _EAppOwnershipFlags_name[81:92],
	128:    _EAppOwnershipFlags_name[92:105],
	256:    _EAppOwnershipFlags_name[105:118],
	512:    _EAppOwnershipFlags_name[118:132],
	1024:   _EAppOwnershipFlags_name[132:146],
	2048:   _EAppOwnershipFlags_name[146:162],
	4096:   _EAppOwnershipFlags_name[162:178],
	8192:   _EAppOwnershipFlags_name[178:193],
	16384:  _EAppOwnershipFlags_name[193:202],
	32768:  _EAppOwnershipFlags_name[202:213],
	65536:  _EAppOwnershipFlags_name[213:231],
	131072: _EAppOwnershipFlags_name[231:237],
	262144: _EAppOwnershipFlags_name[237:248],
}

func (i EAppOwnershipFlags) String() string {
	if str, ok := _EAppOwnershipFlags_map[i]; ok {
		return str
	}
	return "EAppOwnershipFlags(" + strconv.FormatInt(int64(i), 10) + ")"
}
