// Code generated by "stringer -type EAppReleaseState -trimprefix EAppReleaseState_"; DO NOT EDIT.

package internal

import "strconv"

const _EAppReleaseState_name = "UnknownUnavailablePrereleasePreloadOnlyReleased"

var _EAppReleaseState_index = [...]uint8{0, 7, 18, 28, 39, 47}

func (i EAppReleaseState) String() string {
	if i < 0 || i >= EAppReleaseState(len(_EAppReleaseState_index)-1) {
		return "EAppReleaseState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EAppReleaseState_name[_EAppReleaseState_index[i]:_EAppReleaseState_index[i+1]]
}
