// Code generated by "stringer -type EAppType -trimprefix EAppType_"; DO NOT EDIT.

package internal

import "strconv"

const _EAppType_name = "DepotOnlyInvalidGameApplicationToolDemoMedia_DEPRECATEDDLCGuideDriverConfigHardwareFranchiseVideoPluginMusicSeriesComicShortcut"

var _EAppType_map = map[EAppType]string{
	-2147483648: _EAppType_name[0:9],
	0:           _EAppType_name[9:16],
	1:           _EAppType_name[16:20],
	2:           _EAppType_name[20:31],
	4:           _EAppType_name[31:35],
	8:           _EAppType_name[35:39],
	16:          _EAppType_name[39:55],
	32:          _EAppType_name[55:58],
	64:          _EAppType_name[58:63],
	128:         _EAppType_name[63:69],
	256:         _EAppType_name[69:75],
	512:         _EAppType_name[75:83],
	1024:        _EAppType_name[83:92],
	2048:        _EAppType_name[92:97],
	4096:        _EAppType_name[97:103],
	8192:        _EAppType_name[103:108],
	16384:       _EAppType_name[108:114],
	32768:       _EAppType_name[114:119],
	1073741824:  _EAppType_name[119:127],
}

func (i EAppType) String() string {
	if str, ok := _EAppType_map[i]; ok {
		return str
	}
	return "EAppType(" + strconv.FormatInt(int64(i), 10) + ")"
}
