// Code generated by "stringer -type EAudioPlayback -trimprefix EAudioPlayback_"; DO NOT EDIT.

package internal

import "strconv"

const _EAudioPlayback_name = "UndefinedPlayingPausedIdle"

var _EAudioPlayback_index = [...]uint8{0, 9, 16, 22, 26}

func (i EAudioPlayback) String() string {
	if i < 0 || i >= EAudioPlayback(len(_EAudioPlayback_index)-1) {
		return "EAudioPlayback(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EAudioPlayback_name[_EAudioPlayback_index[i]:_EAudioPlayback_index[i+1]]
}
