// Code generated by "stringer -type EAuthSessionResponse -trimprefix EAuthSessionResponse_"; DO NOT EDIT.

package internal

import "strconv"

const _EAuthSessionResponse_name = "OKUserNotConnectedToSteamNoLicenseOrExpiredVACBannedLoggedInElseWhereVACCheckTimedOutAuthTicketCanceledAuthTicketInvalidAlreadyUsedAuthTicketInvalidPublisherIssuedBan"

var _EAuthSessionResponse_index = [...]uint8{0, 2, 25, 43, 52, 69, 85, 103, 131, 148, 166}

func (i EAuthSessionResponse) String() string {
	if i < 0 || i >= EAuthSessionResponse(len(_EAuthSessionResponse_index)-1) {
		return "EAuthSessionResponse(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EAuthSessionResponse_name[_EAuthSessionResponse_index[i]:_EAuthSessionResponse_index[i+1]]
}
