// Code generated by "stringer -type EBeginAuthSessionResult -trimprefix EBeginAuthSessionResult_"; DO NOT EDIT.

package internal

import "strconv"

const _EBeginAuthSessionResult_name = "OKInvalidTicketDuplicateRequestInvalidVersionGameMismatchExpiredTicket"

var _EBeginAuthSessionResult_index = [...]uint8{0, 2, 15, 31, 45, 57, 70}

func (i EBeginAuthSessionResult) String() string {
	if i < 0 || i >= EBeginAuthSessionResult(len(_EBeginAuthSessionResult_index)-1) {
		return "EBeginAuthSessionResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EBeginAuthSessionResult_name[_EBeginAuthSessionResult_index[i]:_EBeginAuthSessionResult_index[i+1]]
}
