// Code generated by "stringer -type EBroadcastUploadResult -trimprefix EBroadcastUploadResult_"; DO NOT EDIT.

package internal

import "strconv"

const _EBroadcastUploadResult_name = "NoneOKInitFailedFrameFailedTimeoutBandwidthExceededLowFPSMissingKeyFramesNoConnectionRelayFailedSettingsChangedMissingAudioTooFarBehindTranscodeBehind"

var _EBroadcastUploadResult_index = [...]uint8{0, 4, 6, 16, 27, 34, 51, 57, 73, 85, 96, 111, 123, 135, 150}

func (i EBroadcastUploadResult) String() string {
	if i < 0 || i >= EBroadcastUploadResult(len(_EBroadcastUploadResult_index)-1) {
		return "EBroadcastUploadResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EBroadcastUploadResult_name[_EBroadcastUploadResult_index[i]:_EBroadcastUploadResult_index[i+1]]
}
