// Code generated by "stringer -type EChatMemberStateChange -trimprefix EChatMemberStateChange_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_EChatMemberStateChange_name_0 = "EnteredLeft"
	_EChatMemberStateChange_name_1 = "Disconnected"
	_EChatMemberStateChange_name_2 = "Kicked"
	_EChatMemberStateChange_name_3 = "Banned"
)

var (
	_EChatMemberStateChange_index_0 = [...]uint8{0, 7, 11}
)

func (i EChatMemberStateChange) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _EChatMemberStateChange_name_0[_EChatMemberStateChange_index_0[i]:_EChatMemberStateChange_index_0[i+1]]
	case i == 4:
		return _EChatMemberStateChange_name_1
	case i == 8:
		return _EChatMemberStateChange_name_2
	case i == 16:
		return _EChatMemberStateChange_name_3
	default:
		return "EChatMemberStateChange(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
