// Code generated by "stringer -type EChatSteamIDInstanceFlags -trimprefix EChatSteamIDInstanceFlags_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_EChatSteamIDInstanceFlags_name_0 = "EChatAccountInstanceMask"
	_EChatSteamIDInstanceFlags_name_1 = "EChatInstanceFlagMMSLobby"
	_EChatSteamIDInstanceFlags_name_2 = "EChatInstanceFlagLobby"
	_EChatSteamIDInstanceFlags_name_3 = "EChatInstanceFlagClan"
)

func (i EChatSteamIDInstanceFlags) String() string {
	switch {
	case i == 4095:
		return _EChatSteamIDInstanceFlags_name_0
	case i == 131072:
		return _EChatSteamIDInstanceFlags_name_1
	case i == 262144:
		return _EChatSteamIDInstanceFlags_name_2
	case i == 524288:
		return _EChatSteamIDInstanceFlags_name_3
	default:
		return "EChatSteamIDInstanceFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
