// Code generated by "stringer -type EChatEntryType -trimprefix EChatEntryType_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_EChatEntryType_name_0 = "InvalidChatMsgTypingInviteGameEmote"
	_EChatEntryType_name_1 = "LeftConversationEnteredWasKickedWasBannedDisconnectedHistoricalChat"
	_EChatEntryType_name_2 = "LinkBlocked"
)

var (
	_EChatEntryType_index_0 = [...]uint8{0, 7, 14, 20, 30, 35}
	_EChatEntryType_index_1 = [...]uint8{0, 16, 23, 32, 41, 53, 67}
)

func (i EChatEntryType) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _EChatEntryType_name_0[_EChatEntryType_index_0[i]:_EChatEntryType_index_0[i+1]]
	case 6 <= i && i <= 11:
		i -= 6
		return _EChatEntryType_name_1[_EChatEntryType_index_1[i]:_EChatEntryType_index_1[i+1]]
	case i == 14:
		return _EChatEntryType_name_2
	default:
		return "EChatEntryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
