// Code generated by "stringer -type EChatRoomEnterResponse -trimprefix EChatRoomEnterResponse_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_EChatRoomEnterResponse_name_0 = "SuccessDoesntExistNotAllowedFullErrorBannedLimitedClanDisabledCommunityBanMemberBlockedYouYouBlockedMember"
	_EChatRoomEnterResponse_name_1 = "RatelimitExceeded"
)

var (
	_EChatRoomEnterResponse_index_0 = [...]uint8{0, 7, 18, 28, 32, 37, 43, 50, 62, 74, 90, 106}
)

func (i EChatRoomEnterResponse) String() string {
	switch {
	case 1 <= i && i <= 11:
		i -= 1
		return _EChatRoomEnterResponse_name_0[_EChatRoomEnterResponse_index_0[i]:_EChatRoomEnterResponse_index_0[i+1]]
	case i == 15:
		return _EChatRoomEnterResponse_name_1
	default:
		return "EChatRoomEnterResponse(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
