// Code generated by "stringer -type ECheckFileSignature -trimprefix ECheckFileSignature_"; DO NOT EDIT.

package internal

import "strconv"

const _ECheckFileSignature_name = "InvalidSignatureValidSignatureFileNotFoundNoSignaturesFoundForThisAppNoSignaturesFoundForThisFile"

var _ECheckFileSignature_index = [...]uint8{0, 16, 30, 42, 69, 97}

func (i ECheckFileSignature) String() string {
	if i < 0 || i >= ECheckFileSignature(len(_ECheckFileSignature_index)-1) {
		return "ECheckFileSignature(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ECheckFileSignature_name[_ECheckFileSignature_index[i]:_ECheckFileSignature_index[i+1]]
}
