// Code generated by "stringer -type EControllerSource -trimprefix EControllerSource_"; DO NOT EDIT.

package internal

import "strconv"

const _EControllerSource_name = "NoneLeftTrackpadRightTrackpadJoystickABXYSwitchLeftTriggerRightTriggerGyroCenterTrackpadRightJoystickDPadKeyMouseCount"

var _EControllerSource_index = [...]uint8{0, 4, 16, 29, 37, 41, 47, 58, 70, 74, 88, 101, 105, 108, 113, 118}

func (i EControllerSource) String() string {
	if i < 0 || i >= EControllerSource(len(_EControllerSource_index)-1) {
		return "EControllerSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EControllerSource_name[_EControllerSource_index[i]:_EControllerSource_index[i+1]]
}
