// Code generated by "stringer -type EControllerSourceMode -trimprefix EControllerSourceMode_"; DO NOT EDIT.

package internal

import "strconv"

const _EControllerSourceMode_name = "NoneDpadButtonsFourButtonsAbsoluteMouseRelativeMouseJoystickMoveJoystickMouseJoystickCameraScrollWheelTriggerTouchMenuMouseJoystickMouseRegionRadialMenuSingleButtonSwitches"

var _EControllerSourceMode_index = [...]uint8{0, 4, 8, 15, 26, 39, 52, 64, 77, 91, 102, 109, 118, 131, 142, 152, 164, 172}

func (i EControllerSourceMode) String() string {
	if i < 0 || i >= EControllerSourceMode(len(_EControllerSourceMode_index)-1) {
		return "EControllerSourceMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EControllerSourceMode_name[_EControllerSourceMode_index[i]:_EControllerSourceMode_index[i+1]]
}
