// Code generated by "stringer -type EDenyReason -trimprefix EDenyReason_"; DO NOT EDIT.

package internal

import "strconv"

const _EDenyReason_name = "EDenyInvalidEDenyInvalidVersionEDenyGenericEDenyNotLoggedOnEDenyNoLicenseEDenyCheaterEDenyLoggedInElseWhereEDenyUnknownTextEDenyIncompatibleAnticheatEDenyMemoryCorruptionEDenyIncompatibleSoftwareEDenySteamConnectionLostEDenySteamConnectionErrorEDenySteamResponseTimedOutEDenySteamValidationStalledEDenySteamOwnerLeftGuestUser"

var _EDenyReason_index = [...]uint16{0, 12, 31, 43, 59, 73, 85, 107, 123, 149, 170, 195, 219, 244, 270, 297, 325}

func (i EDenyReason) String() string {
	if i < 0 || i >= EDenyReason(len(_EDenyReason_index)-1) {
		return "EDenyReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EDenyReason_name[_EDenyReason_index[i]:_EDenyReason_index[i+1]]
}
