// Code generated by "stringer -type EFailureType -trimprefix EFailureType_"; DO NOT EDIT.

package internal

import "strconv"

const _EFailureType_name = "EFailureFlushedCallbackQueueEFailurePipeFail"

var _EFailureType_index = [...]uint8{0, 28, 44}

func (i EFailureType) String() string {
	if i < 0 || i >= EFailureType(len(_EFailureType_index)-1) {
		return "EFailureType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EFailureType_name[_EFailureType_index[i]:_EFailureType_index[i+1]]
}
