// Code generated by "stringer -type EFriendRelationship -trimprefix EFriendRelationship_"; DO NOT EDIT.

package internal

import "strconv"

const _EFriendRelationship_name = "NoneBlockedRequestRecipientFriendRequestInitiatorIgnoredIgnoredFriendSuggested_DEPRECATEDMax"

var _EFriendRelationship_index = [...]uint8{0, 4, 11, 27, 33, 49, 56, 69, 89, 92}

func (i EFriendRelationship) String() string {
	if i < 0 || i >= EFriendRelationship(len(_EFriendRelationship_index)-1) {
		return "EFriendRelationship(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EFriendRelationship_name[_EFriendRelationship_index[i]:_EFriendRelationship_index[i+1]]
}
