// Code generated by "stringer -type EGamepadTextInputLineMode -trimprefix EGamepadTextInputLineMode_"; DO NOT EDIT.

package internal

import "strconv"

const _EGamepadTextInputLineMode_name = "SingleLineMultipleLines"

var _EGamepadTextInputLineMode_index = [...]uint8{0, 10, 23}

func (i EGamepadTextInputLineMode) String() string {
	if i < 0 || i >= EGamepadTextInputLineMode(len(_EGamepadTextInputLineMode_index)-1) {
		return "EGamepadTextInputLineMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EGamepadTextInputLineMode_name[_EGamepadTextInputLineMode_index[i]:_EGamepadTextInputLineMode_index[i+1]]
}
