// Code generated by "stringer -type EGamepadTextInputMode -trimprefix EGamepadTextInputMode_"; DO NOT EDIT.

package internal

import "strconv"

const _EGamepadTextInputMode_name = "NormalPassword"

var _EGamepadTextInputMode_index = [...]uint8{0, 6, 14}

func (i EGamepadTextInputMode) String() string {
	if i < 0 || i >= EGamepadTextInputMode(len(_EGamepadTextInputMode_index)-1) {
		return "EGamepadTextInputMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EGamepadTextInputMode_name[_EGamepadTextInputMode_index[i]:_EGamepadTextInputMode_index[i+1]]
}
