// Code generated by "stringer -type EHTMLMouseButton -trimprefix EHTMLMouseButton_"; DO NOT EDIT.

package internal

import "strconv"

const _EHTMLMouseButton_name = "LeftRightMiddle"

var _EHTMLMouseButton_index = [...]uint8{0, 4, 9, 15}

func (i EHTMLMouseButton) String() string {
	if i < 0 || i >= EHTMLMouseButton(len(_EHTMLMouseButton_index)-1) {
		return "EHTMLMouseButton(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EHTMLMouseButton_name[_EHTMLMouseButton_index[i]:_EHTMLMouseButton_index[i+1]]
}
