// Code generated by "stringer -type EHTMLKeyModifiers -trimprefix EHTMLKeyModifiers_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_EHTMLKeyModifiers_name_0 = "HTMLKeyModifier_NoneHTMLKeyModifier_AltDownHTMLKeyModifier_CtrlDown"
	_EHTMLKeyModifiers_name_1 = "HTMLKeyModifier_ShiftDown"
)

var (
	_EHTMLKeyModifiers_index_0 = [...]uint8{0, 20, 43, 67}
)

func (i EHTMLKeyModifiers) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _EHTMLKeyModifiers_name_0[_EHTMLKeyModifiers_index_0[i]:_EHTMLKeyModifiers_index_0[i+1]]
	case i == 4:
		return _EHTMLKeyModifiers_name_1
	default:
		return "EHTMLKeyModifiers(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
