// Code generated by "stringer -type EHTTPStatusCode -trimprefix EHTTPStatusCode_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_EHTTPStatusCode_name_0 = "Invalid"
	_EHTTPStatusCode_name_1 = "100Continue101SwitchingProtocols"
	_EHTTPStatusCode_name_2 = "200OK201Created202Accepted203NonAuthoritative204NoContent205ResetContent206PartialContent"
	_EHTTPStatusCode_name_3 = "300MultipleChoices301MovedPermanently302Found303SeeOther304NotModified305UseProxy"
	_EHTTPStatusCode_name_4 = "307TemporaryRedirect"
	_EHTTPStatusCode_name_5 = "400BadRequest401Unauthorized402PaymentRequired403Forbidden404NotFound405MethodNotAllowed406NotAcceptable407ProxyAuthRequired408RequestTimeout409Conflict410Gone411LengthRequired412PreconditionFailed413RequestEntityTooLarge414RequestURITooLong415UnsupportedMediaType416RequestedRangeNotSatisfiable417ExpectationFailed4xxUnknown"
	_EHTTPStatusCode_name_6 = "429TooManyRequests"
	_EHTTPStatusCode_name_7 = "500InternalServerError501NotImplemented502BadGateway503ServiceUnavailable504GatewayTimeout505HTTPVersionNotSupported"
	_EHTTPStatusCode_name_8 = "5xxUnknown"
)

var (
	_EHTTPStatusCode_index_1 = [...]uint8{0, 11, 32}
	_EHTTPStatusCode_index_2 = [...]uint8{0, 5, 15, 26, 45, 57, 72, 89}
	_EHTTPStatusCode_index_3 = [...]uint8{0, 18, 37, 45, 56, 70, 81}
	_EHTTPStatusCode_index_5 = [...]uint16{0, 13, 28, 46, 58, 69, 88, 104, 124, 141, 152, 159, 176, 197, 221, 241, 264, 295, 315, 325}
	_EHTTPStatusCode_index_7 = [...]uint8{0, 22, 39, 52, 73, 90, 116}
)

func (i EHTTPStatusCode) String() string {
	switch {
	case i == 0:
		return _EHTTPStatusCode_name_0
	case 100 <= i && i <= 101:
		i -= 100
		return _EHTTPStatusCode_name_1[_EHTTPStatusCode_index_1[i]:_EHTTPStatusCode_index_1[i+1]]
	case 200 <= i && i <= 206:
		i -= 200
		return _EHTTPStatusCode_name_2[_EHTTPStatusCode_index_2[i]:_EHTTPStatusCode_index_2[i+1]]
	case 300 <= i && i <= 305:
		i -= 300
		return _EHTTPStatusCode_name_3[_EHTTPStatusCode_index_3[i]:_EHTTPStatusCode_index_3[i+1]]
	case i == 307:
		return _EHTTPStatusCode_name_4
	case 400 <= i && i <= 418:
		i -= 400
		return _EHTTPStatusCode_name_5[_EHTTPStatusCode_index_5[i]:_EHTTPStatusCode_index_5[i+1]]
	case i == 429:
		return _EHTTPStatusCode_name_6
	case 500 <= i && i <= 505:
		i -= 500
		return _EHTTPStatusCode_name_7[_EHTTPStatusCode_index_7[i]:_EHTTPStatusCode_index_7[i+1]]
	case i == 599:
		return _EHTTPStatusCode_name_8
	default:
		return "EHTTPStatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
