// Code generated by "stringer -type EItemPreviewType -trimprefix EItemPreviewType_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_EItemPreviewType_name_0 = "ImageYouTubeVideoSketchfabEnvironmentMap_HorizontalCrossEnvironmentMap_LatLong"
	_EItemPreviewType_name_1 = "ReservedMax"
)

var (
	_EItemPreviewType_index_0 = [...]uint8{0, 5, 17, 26, 56, 78}
)

func (i EItemPreviewType) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _EItemPreviewType_name_0[_EItemPreviewType_index_0[i]:_EItemPreviewType_index_0[i+1]]
	case i == 255:
		return _EItemPreviewType_name_1
	default:
		return "EItemPreviewType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
