// Code generated by "stringer -type EItemUpdateStatus -trimprefix EItemUpdateStatus_"; DO NOT EDIT.

package internal

import "strconv"

const _EItemUpdateStatus_name = "InvalidPreparingConfigPreparingContentUploadingContentUploadingPreviewFileCommittingChanges"

var _EItemUpdateStatus_index = [...]uint8{0, 7, 22, 38, 54, 74, 91}

func (i EItemUpdateStatus) String() string {
	if i < 0 || i >= EItemUpdateStatus(len(_EItemUpdateStatus_index)-1) {
		return "EItemUpdateStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EItemUpdateStatus_name[_EItemUpdateStatus_index[i]:_EItemUpdateStatus_index[i+1]]
}
