// Code generated by "stringer -type EItemState -trimprefix EItemState_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_EItemState_name_0 = "NoneSubscribedLegacyItem"
	_EItemState_name_1 = "Installed"
	_EItemState_name_2 = "NeedsUpdate"
	_EItemState_name_3 = "Downloading"
	_EItemState_name_4 = "DownloadPending"
)

var (
	_EItemState_index_0 = [...]uint8{0, 4, 14, 24}
)

func (i EItemState) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _EItemState_name_0[_EItemState_index_0[i]:_EItemState_index_0[i+1]]
	case i == 4:
		return _EItemState_name_1
	case i == 8:
		return _EItemState_name_2
	case i == 16:
		return _EItemState_name_3
	case i == 32:
		return _EItemState_name_4
	default:
		return "EItemState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
