// Code generated by "stringer -type ELaunchOptionType -trimprefix ELaunchOptionType_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_ELaunchOptionType_name_0 = "NoneDefaultSafeModeMultiplayerConfigOpenVRServerEditorManualBenchmarkOption1Option2Option3OculusVROpenVROverlayOSVR"
	_ELaunchOptionType_name_1 = "Dialog"
)

var (
	_ELaunchOptionType_index_0 = [...]uint8{0, 4, 11, 19, 30, 36, 42, 48, 54, 60, 69, 76, 83, 90, 98, 111, 115}
)

func (i ELaunchOptionType) String() string {
	switch {
	case 0 <= i && i <= 15:
		return _ELaunchOptionType_name_0[_ELaunchOptionType_index_0[i]:_ELaunchOptionType_index_0[i+1]]
	case i == 1000:
		return _ELaunchOptionType_name_1
	default:
		return "ELaunchOptionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
