// Code generated by "stringer -type ELeaderboardUploadScoreMethod -trimprefix ELeaderboardUploadScoreMethod_"; DO NOT EDIT.

package internal

import "strconv"

const _ELeaderboardUploadScoreMethod_name = "NoneKeepBestForceUpdate"

var _ELeaderboardUploadScoreMethod_index = [...]uint8{0, 4, 12, 23}

func (i ELeaderboardUploadScoreMethod) String() string {
	if i < 0 || i >= ELeaderboardUploadScoreMethod(len(_ELeaderboardUploadScoreMethod_index)-1) {
		return "ELeaderboardUploadScoreMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ELeaderboardUploadScoreMethod_name[_ELeaderboardUploadScoreMethod_index[i]:_ELeaderboardUploadScoreMethod_index[i+1]]
}
