// Code generated by "stringer -type ELeaderboardSortMethod -trimprefix ELeaderboardSortMethod_"; DO NOT EDIT.

package internal

import "strconv"

const _ELeaderboardSortMethod_name = "NoneAscendingDescending"

var _ELeaderboardSortMethod_index = [...]uint8{0, 4, 13, 23}

func (i ELeaderboardSortMethod) String() string {
	if i < 0 || i >= ELeaderboardSortMethod(len(_ELeaderboardSortMethod_index)-1) {
		return "ELeaderboardSortMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ELeaderboardSortMethod_name[_ELeaderboardSortMethod_index[i]:_ELeaderboardSortMethod_index[i+1]]
}
