// Code generated by "stringer -type ELeaderboardDataRequest -trimprefix ELeaderboardDataRequest_"; DO NOT EDIT.

package internal

import "strconv"

const _ELeaderboardDataRequest_name = "GlobalGlobalAroundUserFriendsUsers"

var _ELeaderboardDataRequest_index = [...]uint8{0, 6, 22, 29, 34}

func (i ELeaderboardDataRequest) String() string {
	if i < 0 || i >= ELeaderboardDataRequest(len(_ELeaderboardDataRequest_index)-1) {
		return "ELeaderboardDataRequest(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ELeaderboardDataRequest_name[_ELeaderboardDataRequest_index[i]:_ELeaderboardDataRequest_index[i+1]]
}
