// Code generated by "stringer -type ELobbyDistanceFilter -trimprefix ELobbyDistanceFilter_"; DO NOT EDIT.

package internal

import "strconv"

const _ELobbyDistanceFilter_name = "CloseDefaultFarWorldwide"

var _ELobbyDistanceFilter_index = [...]uint8{0, 5, 12, 15, 24}

func (i ELobbyDistanceFilter) String() string {
	if i < 0 || i >= ELobbyDistanceFilter(len(_ELobbyDistanceFilter_index)-1) {
		return "ELobbyDistanceFilter(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ELobbyDistanceFilter_name[_ELobbyDistanceFilter_index[i]:_ELobbyDistanceFilter_index[i+1]]
}
