// Code generated by "stringer -type ELobbyType -trimprefix ELobbyType_"; DO NOT EDIT.

package internal

import "strconv"

const _ELobbyType_name = "PrivateFriendsOnlyPublicInvisible"

var _ELobbyType_index = [...]uint8{0, 7, 18, 24, 33}

func (i ELobbyType) String() string {
	if i < 0 || i >= ELobbyType(len(_ELobbyType_index)-1) {
		return "ELobbyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ELobbyType_name[_ELobbyType_index[i]:_ELobbyType_index[i+1]]
}
