// Code generated by "stringer -type ELobbyComparison -trimprefix ELobbyComparison_"; DO NOT EDIT.

package internal

import "strconv"

const _ELobbyComparison_name = "EqualToOrLessThanLessThanEqualGreaterThanEqualToOrGreaterThanNotEqual"

var _ELobbyComparison_index = [...]uint8{0, 17, 25, 30, 41, 61, 69}

func (i ELobbyComparison) String() string {
	i -= -2
	if i < 0 || i >= ELobbyComparison(len(_ELobbyComparison_index)-1) {
		return "ELobbyComparison(" + strconv.FormatInt(int64(i+-2), 10) + ")"
	}
	return _ELobbyComparison_name[_ELobbyComparison_index[i]:_ELobbyComparison_index[i+1]]
}
