// Code generated by "stringer -type EMarketingMessageFlags -trimprefix EMarketingMessageFlags_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_EMarketingMessageFlags_name_0 = "NoneHighPriorityPlatformWindows"
	_EMarketingMessageFlags_name_1 = "PlatformMac"
	_EMarketingMessageFlags_name_2 = "PlatformLinux"
	_EMarketingMessageFlags_name_3 = "PlatformRestrictions"
)

var (
	_EMarketingMessageFlags_index_0 = [...]uint8{0, 4, 16, 31}
)

func (i EMarketingMessageFlags) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _EMarketingMessageFlags_name_0[_EMarketingMessageFlags_index_0[i]:_EMarketingMessageFlags_index_0[i+1]]
	case i == 4:
		return _EMarketingMessageFlags_name_1
	case i == 8:
		return _EMarketingMessageFlags_name_2
	case i == 14:
		return _EMarketingMessageFlags_name_3
	default:
		return "EMarketingMessageFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
