// Code generated by "stringer -type EMatchMakingServerResponse -trimprefix EMatchMakingServerResponse_"; DO NOT EDIT.

package internal

import "strconv"

const _EMatchMakingServerResponse_name = "ServerRespondedServerFailedToRespondNoServersListedOnMasterServer"

var _EMatchMakingServerResponse_index = [...]uint8{0, 15, 36, 65}

func (i EMatchMakingServerResponse) String() string {
	if i < 0 || i >= EMatchMakingServerResponse(len(_EMatchMakingServerResponse_index)-1) {
		return "EMatchMakingServerResponse(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EMatchMakingServerResponse_name[_EMatchMakingServerResponse_index[i]:_EMatchMakingServerResponse_index[i+1]]
}
