// Code generated by "stringer -type ENotificationPosition -trimprefix ENotificationPosition_"; DO NOT EDIT.

package internal

import "strconv"

const _ENotificationPosition_name = "EPositionTopLeftEPositionTopRightEPositionBottomLeftEPositionBottomRight"

var _ENotificationPosition_index = [...]uint8{0, 16, 33, 52, 72}

func (i ENotificationPosition) String() string {
	if i < 0 || i >= ENotificationPosition(len(_ENotificationPosition_index)-1) {
		return "ENotificationPosition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ENotificationPosition_name[_ENotificationPosition_index[i]:_ENotificationPosition_index[i+1]]
}
