// Code generated by "stringer -type EOverlayToStoreFlag -trimprefix EOverlayToStoreFlag_"; DO NOT EDIT.

package internal

import "strconv"

const _EOverlayToStoreFlag_name = "NoneAddToCartAddToCartAndShow"

var _EOverlayToStoreFlag_index = [...]uint8{0, 4, 13, 29}

func (i EOverlayToStoreFlag) String() string {
	if i < 0 || i >= EOverlayToStoreFlag(len(_EOverlayToStoreFlag_index)-1) {
		return "EOverlayToStoreFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EOverlayToStoreFlag_name[_EOverlayToStoreFlag_index[i]:_EOverlayToStoreFlag_index[i+1]]
}
