// Code generated by "stringer -type EP2PSend -trimprefix EP2PSend_"; DO NOT EDIT.

package internal

import "strconv"

const _EP2PSend_name = "UnreliableUnreliableNoDelayReliableReliableWithBuffering"

var _EP2PSend_index = [...]uint8{0, 10, 27, 35, 56}

func (i EP2PSend) String() string {
	if i < 0 || i >= EP2PSend(len(_EP2PSend_index)-1) {
		return "EP2PSend(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EP2PSend_name[_EP2PSend_index[i]:_EP2PSend_index[i+1]]
}
