// Code generated by "stringer -type EPersonaState -trimprefix EPersonaState_"; DO NOT EDIT.

package internal

import "strconv"

const _EPersonaState_name = "OfflineOnlineBusyAwaySnoozeLookingToTradeLookingToPlayMax"

var _EPersonaState_index = [...]uint8{0, 7, 13, 17, 21, 27, 41, 54, 57}

func (i EPersonaState) String() string {
	if i < 0 || i >= EPersonaState(len(_EPersonaState_index)-1) {
		return "EPersonaState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EPersonaState_name[_EPersonaState_index[i]:_EPersonaState_index[i+1]]
}
