// Code generated by "stringer -type ERegisterActivationCodeResult -trimprefix ERegisterActivationCodeResult_"; DO NOT EDIT.

package internal

import "strconv"

const _ERegisterActivationCodeResult_name = "OKFailAlreadyRegisteredTimeoutERegisterActivationCodeAlreadyOwned"

var _ERegisterActivationCodeResult_index = [...]uint8{0, 2, 6, 23, 30, 65}

func (i ERegisterActivationCodeResult) String() string {
	if i < 0 || i >= ERegisterActivationCodeResult(len(_ERegisterActivationCodeResult_index)-1) {
		return "ERegisterActivationCodeResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ERegisterActivationCodeResult_name[_ERegisterActivationCodeResult_index[i]:_ERegisterActivationCodeResult_index[i+1]]
}
