// Code generated by "stringer -type ERemoteStoragePublishedFileVisibility -trimprefix ERemoteStoragePublishedFileVisibility_"; DO NOT EDIT.

package internal

import "strconv"

const _ERemoteStoragePublishedFileVisibility_name = "PublicFriendsOnlyPrivate"

var _ERemoteStoragePublishedFileVisibility_index = [...]uint8{0, 6, 17, 24}

func (i ERemoteStoragePublishedFileVisibility) String() string {
	if i < 0 || i >= ERemoteStoragePublishedFileVisibility(len(_ERemoteStoragePublishedFileVisibility_index)-1) {
		return "ERemoteStoragePublishedFileVisibility(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ERemoteStoragePublishedFileVisibility_name[_ERemoteStoragePublishedFileVisibility_index[i]:_ERemoteStoragePublishedFileVisibility_index[i+1]]
}
