// Code generated by "stringer -type EResult -trimprefix EResult_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_EResult_name_0 = "OKFailNoConnection"
	_EResult_name_1 = "InvalidPasswordLoggedInElsewhereInvalidProtocolVerInvalidParamFileNotFoundBusyInvalidStateInvalidNameInvalidEmailDuplicateNameAccessDeniedTimeoutBannedAccountNotFoundInvalidSteamIDServiceUnavailableNotLoggedOnPendingEncryptionFailureInsufficientPrivilegeLimitExceededRevokedExpiredAlreadyRedeemedDuplicateRequestAlreadyOwnedIPNotFoundPersistFailedLockingFailedLogonSessionReplacedConnectFailedHandshakeFailedIOFailureRemoteDisconnectShoppingCartNotFoundBlockedIgnoredNoMatchAccountDisabledServiceReadOnlyAccountNotFeaturedAdministratorOKContentVersionTryAnotherCMPasswordRequiredToKickSessionAlreadyLoggedInElsewhereSuspendedCancelledDataCorruptionDiskFullRemoteCallFailedPasswordUnsetExternalAccountUnlinkedPSNTicketInvalidExternalAccountAlreadyLinkedRemoteFileConflictIllegalPasswordSameAsPreviousValueAccountLogonDeniedCannotUseOldPasswordInvalidLoginAuthCodeAccountLogonDeniedNoMailHardwareNotCapableOfIPTIPTInitErrorParentalControlRestrictedFacebookQueryErrorExpiredLoginAuthCodeIPLoginRestrictionFailedAccountLockedDownAccountLogonDeniedVerifiedEmailRequiredNoMatchingURLBadResponseRequirePasswordReEntryValueOutOfRangeUnexpectedErrorDisabledInvalidCEGSubmissionRestrictedDeviceRegionLockedRateLimitExceededAccountLoginDeniedNeedTwoFactorItemDeletedAccountLoginDeniedThrottleTwoFactorCodeMismatchTwoFactorActivationCodeMismatchAccountAssociatedToMultiplePartnersNotModifiedNoMobileDeviceTimeNotSyncedSmsCodeFailedAccountLimitExceededAccountActivityLimitExceededPhoneActivityLimitExceededRefundToWalletEmailSendFailureNotSettledNeedCaptchaGSLTDeniedGSOwnerDeniedInvalidItemTypeIPBannedGSLTExpiredInsufficientFundsTooManyPendingNoSiteLicensesFoundWGNetworkSendExceededAccountNotFriendsLimitedUserAccount"
)

var (
	_EResult_index_0 = [...]uint8{0, 2, 6, 18}
	_EResult_index_1 = [...]uint16{0, 15, 32, 50, 62, 74, 78, 90, 101, 113, 126, 138, 145, 151, 166, 180, 198, 209, 216, 233, 254, 267, 274, 281, 296, 312, 324, 334, 347, 360, 380, 393, 408, 417, 433, 453, 460, 467, 474, 489, 504, 522, 537, 551, 563, 592, 616, 625, 634, 648, 656, 672, 685, 708, 724, 752, 770, 785, 804, 822, 842, 862, 886, 909, 921, 946, 964, 984, 1008, 1025, 1064, 1077, 1088, 1110, 1125, 1140, 1148, 1168, 1184, 1196, 1213, 1244, 1255, 1281, 1302, 1333, 1368, 1379, 1393, 1406, 1419, 1439, 1467, 1493, 1507, 1523, 1533, 1544, 1554, 1567, 1582, 1590, 1601, 1618, 1632, 1651, 1672, 1689, 1707}
)

func (i EResult) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _EResult_name_0[_EResult_index_0[i]:_EResult_index_0[i+1]]
	case 5 <= i && i <= 112:
		i -= 5
		return _EResult_name_1[_EResult_index_1[i]:_EResult_index_1[i+1]]
	default:
		return "EResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
