// Code generated by "stringer -type EServerMode -trimprefix EServerMode_"; DO NOT EDIT.

package internal

import "strconv"

const _EServerMode_name = "InvalidNoAuthenticationAuthenticationAuthenticationAndSecure"

var _EServerMode_index = [...]uint8{0, 7, 23, 37, 60}

func (i EServerMode) String() string {
	if i < 0 || i >= EServerMode(len(_EServerMode_index)-1) {
		return "EServerMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EServerMode_name[_EServerMode_index[i]:_EServerMode_index[i+1]]
}
