// Code generated by "stringer -type ESNetSocketConnectionType -trimprefix ESNetSocketConnectionType_"; DO NOT EDIT.

package internal

import "strconv"

const _ESNetSocketConnectionType_name = "NotConnectedUDPUDPRelay"

var _ESNetSocketConnectionType_index = [...]uint8{0, 12, 15, 23}

func (i ESNetSocketConnectionType) String() string {
	if i < 0 || i >= ESNetSocketConnectionType(len(_ESNetSocketConnectionType_index)-1) {
		return "ESNetSocketConnectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ESNetSocketConnectionType_name[_ESNetSocketConnectionType_index[i]:_ESNetSocketConnectionType_index[i+1]]
}
