// Code generated by "stringer -type ESNetSocketState -trimprefix ESNetSocketState_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_ESNetSocketState_name_0 = "InvalidConnected"
	_ESNetSocketState_name_1 = "InitiatedLocalCandidatesFoundReceivedRemoteCandidates"
	_ESNetSocketState_name_2 = "ChallengeHandshake"
	_ESNetSocketState_name_3 = "DisconnectingLocalDisconnectTimeoutDuringConnectRemoteEndDisconnectedConnectionBroken"
)

var (
	_ESNetSocketState_index_0 = [...]uint8{0, 7, 16}
	_ESNetSocketState_index_1 = [...]uint8{0, 9, 29, 53}
	_ESNetSocketState_index_3 = [...]uint8{0, 13, 28, 48, 69, 85}
)

func (i ESNetSocketState) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _ESNetSocketState_name_0[_ESNetSocketState_index_0[i]:_ESNetSocketState_index_0[i+1]]
	case 10 <= i && i <= 12:
		i -= 10
		return _ESNetSocketState_name_1[_ESNetSocketState_index_1[i]:_ESNetSocketState_index_1[i+1]]
	case i == 15:
		return _ESNetSocketState_name_2
	case 21 <= i && i <= 25:
		i -= 21
		return _ESNetSocketState_name_3[_ESNetSocketState_index_3[i]:_ESNetSocketState_index_3[i+1]]
	default:
		return "ESNetSocketState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
