// Code generated by "stringer -type ESteamControllerPad -trimprefix ESteamControllerPad_"; DO NOT EDIT.

package internal

import "strconv"

const _ESteamControllerPad_name = "LeftRight"

var _ESteamControllerPad_index = [...]uint8{0, 4, 9}

func (i ESteamControllerPad) String() string {
	if i < 0 || i >= ESteamControllerPad(len(_ESteamControllerPad_index)-1) {
		return "ESteamControllerPad(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ESteamControllerPad_name[_ESteamControllerPad_index[i]:_ESteamControllerPad_index[i+1]]
}
