// Code generated by "stringer -type ESteamAPICallFailure -trimprefix ESteamAPICallFailure_"; DO NOT EDIT.

package internal

import "strconv"

const _ESteamAPICallFailure_name = "NoneSteamGoneNetworkFailureInvalidHandleMismatchedCallback"

var _ESteamAPICallFailure_index = [...]uint8{0, 4, 13, 27, 40, 58}

func (i ESteamAPICallFailure) String() string {
	i -= -1
	if i < 0 || i >= ESteamAPICallFailure(len(_ESteamAPICallFailure_index)-1) {
		return "ESteamAPICallFailure(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _ESteamAPICallFailure_name[_ESteamAPICallFailure_index[i]:_ESteamAPICallFailure_index[i+1]]
}
