// Code generated by "stringer -type ESteamInputType -trimprefix ESteamInputType_"; DO NOT EDIT.

package internal

import "strconv"

const _ESteamInputType_name = "UnknownSteamControllerXBox360ControllerXBoxOneControllerGenericXInputPS4Controller"

var _ESteamInputType_index = [...]uint8{0, 7, 22, 39, 56, 69, 82}

func (i ESteamInputType) String() string {
	if i < 0 || i >= ESteamInputType(len(_ESteamInputType_index)-1) {
		return "ESteamInputType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ESteamInputType_name[_ESteamInputType_index[i]:_ESteamInputType_index[i+1]]
}
