// Code generated by "stringer -type ESteamUserStatType -trimprefix ESteamUserStatType_"; DO NOT EDIT.

package internal

import "strconv"

const _ESteamUserStatType_name = "INVALIDINTFLOATAVGRATEACHIEVEMENTSGROUPACHIEVEMENTSMAX"

var _ESteamUserStatType_index = [...]uint8{0, 7, 10, 15, 22, 34, 51, 54}

func (i ESteamUserStatType) String() string {
	if i < 0 || i >= ESteamUserStatType(len(_ESteamUserStatType_index)-1) {
		return "ESteamUserStatType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ESteamUserStatType_name[_ESteamUserStatType_index[i]:_ESteamUserStatType_index[i+1]]
}
