// Code generated by "stringer -type ESteamItemFlags -trimprefix ESteamItemFlags_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_ESteamItemFlags_name_0 = "ESteamItemNoTrade"
	_ESteamItemFlags_name_1 = "ESteamItemRemoved"
	_ESteamItemFlags_name_2 = "ESteamItemConsumed"
)

func (i ESteamItemFlags) String() string {
	switch {
	case i == 1:
		return _ESteamItemFlags_name_0
	case i == 256:
		return _ESteamItemFlags_name_1
	case i == 512:
		return _ESteamItemFlags_name_2
	default:
		return "ESteamItemFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
