// Code generated by "stringer -type EUGCReadAction -trimprefix EUGCReadAction_"; DO NOT EDIT.

package internal

import "strconv"

const _EUGCReadAction_name = "EUGCRead_ContinueReadingUntilFinishedEUGCRead_ContinueReadingEUGCRead_Close"

var _EUGCReadAction_index = [...]uint8{0, 37, 61, 75}

func (i EUGCReadAction) String() string {
	if i < 0 || i >= EUGCReadAction(len(_EUGCReadAction_index)-1) {
		return "EUGCReadAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EUGCReadAction_name[_EUGCReadAction_index[i]:_EUGCReadAction_index[i+1]]
}
