// Code generated by "stringer -type EUGCMatchingUGCType -trimprefix EUGCMatchingUGCType_"; DO NOT EDIT.

package internal

import "strconv"

const _EUGCMatchingUGCType_name = "AllItemsItems_MtxItems_ReadyToUseCollectionsArtworkVideosScreenshotsAllGuidesWebGuidesIntegratedGuidesUsableInGameControllerBindingsGameManagedItems"

var _EUGCMatchingUGCType_index = [...]uint8{0, 3, 8, 17, 33, 44, 51, 57, 68, 77, 86, 102, 114, 132, 148}

func (i EUGCMatchingUGCType) String() string {
	i -= -1
	if i < 0 || i >= EUGCMatchingUGCType(len(_EUGCMatchingUGCType_index)-1) {
		return "EUGCMatchingUGCType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _EUGCMatchingUGCType_name[_EUGCMatchingUGCType_index[i]:_EUGCMatchingUGCType_index[i+1]]
}
