// Code generated by "stringer -type EUniverse -trimprefix EUniverse_"; DO NOT EDIT.

package internal

import "strconv"

const _EUniverse_name = "InvalidPublicBetaInternalDevMax"

var _EUniverse_index = [...]uint8{0, 7, 13, 17, 25, 28, 31}

func (i EUniverse) String() string {
	if i < 0 || i >= EUniverse(len(_EUniverse_index)-1) {
		return "EUniverse(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EUniverse_name[_EUniverse_index[i]:_EUniverse_index[i+1]]
}
