// Code generated by "stringer -type EUserRestriction -trimprefix EUserRestriction_"; DO NOT EDIT.

package internal

import "strconv"

const (
	_EUserRestriction_name_0 = "nUserRestrictionNonenUserRestrictionUnknownnUserRestrictionAnyChat"
	_EUserRestriction_name_1 = "nUserRestrictionVoiceChat"
	_EUserRestriction_name_2 = "nUserRestrictionGroupChat"
	_EUserRestriction_name_3 = "nUserRestrictionRating"
	_EUserRestriction_name_4 = "nUserRestrictionGameInvites"
	_EUserRestriction_name_5 = "nUserRestrictionTrading"
)

var (
	_EUserRestriction_index_0 = [...]uint8{0, 20, 43, 66}
)

func (i EUserRestriction) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _EUserRestriction_name_0[_EUserRestriction_index_0[i]:_EUserRestriction_index_0[i+1]]
	case i == 4:
		return _EUserRestriction_name_1
	case i == 8:
		return _EUserRestriction_name_2
	case i == 16:
		return _EUserRestriction_name_3
	case i == 32:
		return _EUserRestriction_name_4
	case i == 64:
		return _EUserRestriction_name_5
	default:
		return "EUserRestriction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
