// Code generated by "stringer -type EUserHasLicenseForAppResult -trimprefix EUserHasLicenseForAppResult_"; DO NOT EDIT.

package internal

import "strconv"

const _EUserHasLicenseForAppResult_name = "EUserHasLicenseResultHasLicenseEUserHasLicenseResultDoesNotHaveLicenseEUserHasLicenseResultNoAuth"

var _EUserHasLicenseForAppResult_index = [...]uint8{0, 31, 70, 97}

func (i EUserHasLicenseForAppResult) String() string {
	if i < 0 || i >= EUserHasLicenseForAppResult(len(_EUserHasLicenseForAppResult_index)-1) {
		return "EUserHasLicenseForAppResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EUserHasLicenseForAppResult_name[_EUserHasLicenseForAppResult_index[i]:_EUserHasLicenseForAppResult_index[i+1]]
}
