// Code generated by "stringer -type EUserUGCListSortOrder -trimprefix EUserUGCListSortOrder_"; DO NOT EDIT.

package internal

import "strconv"

const _EUserUGCListSortOrder_name = "CreationOrderDescCreationOrderAscTitleAscLastUpdatedDescSubscriptionDateDescVoteScoreDescForModeration"

var _EUserUGCListSortOrder_index = [...]uint8{0, 17, 33, 41, 56, 76, 89, 102}

func (i EUserUGCListSortOrder) String() string {
	if i < 0 || i >= EUserUGCListSortOrder(len(_EUserUGCListSortOrder_index)-1) {
		return "EUserUGCListSortOrder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EUserUGCListSortOrder_name[_EUserUGCListSortOrder_index[i]:_EUserUGCListSortOrder_index[i+1]]
}
