// Code generated by "stringer -type EUserUGCList -trimprefix EUserUGCList_"; DO NOT EDIT.

package internal

import "strconv"

const _EUserUGCList_name = "PublishedVotedOnVotedUpVotedDownWillVoteLaterFavoritedSubscribedUsedOrPlayedFollowed"

var _EUserUGCList_index = [...]uint8{0, 9, 16, 23, 32, 45, 54, 64, 76, 84}

func (i EUserUGCList) String() string {
	if i < 0 || i >= EUserUGCList(len(_EUserUGCList_index)-1) {
		return "EUserUGCList(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EUserUGCList_name[_EUserUGCList_index[i]:_EUserUGCList_index[i+1]]
}
