// Code generated by "stringer -type EWorkshopEnumerationType -trimprefix EWorkshopEnumerationType_"; DO NOT EDIT.

package internal

import "strconv"

const _EWorkshopEnumerationType_name = "RankedByVoteRecentTrendingFavoritesOfFriendsVotedByFriendsContentByFriendsRecentFromFollowedUsers"

var _EWorkshopEnumerationType_index = [...]uint8{0, 12, 18, 26, 44, 58, 74, 97}

func (i EWorkshopEnumerationType) String() string {
	if i < 0 || i >= EWorkshopEnumerationType(len(_EWorkshopEnumerationType_index)-1) {
		return "EWorkshopEnumerationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EWorkshopEnumerationType_name[_EWorkshopEnumerationType_index[i]:_EWorkshopEnumerationType_index[i+1]]
}
