// Code generated by "stringer -type EWorkshopVote -trimprefix EWorkshopVote_"; DO NOT EDIT.

package internal

import "strconv"

const _EWorkshopVote_name = "UnvotedForAgainstLater"

var _EWorkshopVote_index = [...]uint8{0, 7, 10, 17, 22}

func (i EWorkshopVote) String() string {
	if i < 0 || i >= EWorkshopVote(len(_EWorkshopVote_index)-1) {
		return "EWorkshopVote(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EWorkshopVote_name[_EWorkshopVote_index[i]:_EWorkshopVote_index[i+1]]
}
