// Code generated by "stringer -type EWorkshopFileAction -trimprefix EWorkshopFileAction_"; DO NOT EDIT.

package internal

import "strconv"

const _EWorkshopFileAction_name = "PlayedCompleted"

var _EWorkshopFileAction_index = [...]uint8{0, 6, 15}

func (i EWorkshopFileAction) String() string {
	if i < 0 || i >= EWorkshopFileAction(len(_EWorkshopFileAction_index)-1) {
		return "EWorkshopFileAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EWorkshopFileAction_name[_EWorkshopFileAction_index[i]:_EWorkshopFileAction_index[i+1]]
}
