// Code generated by "stringer -type EWorkshopVideoProvider -trimprefix EWorkshopVideoProvider_"; DO NOT EDIT.

package internal

import "strconv"

const _EWorkshopVideoProvider_name = "NoneYoutube"

var _EWorkshopVideoProvider_index = [...]uint8{0, 4, 11}

func (i EWorkshopVideoProvider) String() string {
	if i < 0 || i >= EWorkshopVideoProvider(len(_EWorkshopVideoProvider_index)-1) {
		return "EWorkshopVideoProvider(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EWorkshopVideoProvider_name[_EWorkshopVideoProvider_index[i]:_EWorkshopVideoProvider_index[i+1]]
}
