// Code generated by "stringer -type EWorkshopFileType -trimprefix EWorkshopFileType_"; DO NOT EDIT.

package internal

import "strconv"

const _EWorkshopFileType_name = "FirstMicrotransactionCollectionArtVideoScreenshotGameSoftwareConceptWebGuideIntegratedGuideMerchControllerBindingSteamworksAccessInviteSteamVideoGameManagedItemMax"

var _EWorkshopFileType_index = [...]uint8{0, 5, 21, 31, 34, 39, 49, 53, 61, 68, 76, 91, 96, 113, 135, 145, 160, 163}

func (i EWorkshopFileType) String() string {
	if i < 0 || i >= EWorkshopFileType(len(_EWorkshopFileType_index)-1) {
		return "EWorkshopFileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EWorkshopFileType_name[_EWorkshopFileType_index[i]:_EWorkshopFileType_index[i+1]]
}
